name: build-binary

on:
  push:
    tags:
      - "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Bootstrap
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make bootstrap
        echo "go-bindata version:" $(go-bindata -version)
    - name: Build frontend assets
      run: |
        echo "Node version:" $(node -v)
        echo "Npm version:" $(npm -v)
        make build-web
        export PATH=$PATH:$(go env GOPATH)/bin
        make build-assets
    - name: Build all arch binary
      run: make build-all-arch

    - name: Upload to Release
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        make pack-arch TAG=${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
