name: build-binary

on:
  push:
    tags:
      - "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Bootstrap
      run: |
        cd server
        go mod download
        cd ../web
        rm -f package-lock.json
        npm i --registry=https://registry.npmjs.org/
    - name: Install go-bindata
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u github.com/go-bindata/go-bindata/...
        echo "go-bindata version:" $(go-bindata -version)
    - name: Build frontend assets
      run: |
        echo "Node version:" $(node -v)
        echo "Npm version:" $(npm -v)
        make build-web
        export PATH=$PATH:$(go env GOPATH)/bin
        make build-assets
    - name: Build all arch binary
      run: make build-all-arch

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: build/arch/
